### ISSUE TITLE
Traktor 2

### ISSUE THREAD

**Issue by technomorph** [ErikMinekus/traktor-api-client#1]

**Comment by technomorph** [comment]
Is it possible to get this working with Traktor 2?

**Comment by ErikMinekus** [comment]
What's not working with Traktor 2?

**Comment by technomorph** [comment]
Traktor Crashes.....
Only thing I can think of is a problem with declaring the deckLetter property as a string
or the String.fromCharCode function.

readonly property string    deckLetter:  String.fromCharCode(65 + deckId)



 here's a bit of the crash log..

Process:               Traktor [14421]
Path:                  /Applications/Native Instruments/*/Traktor.app/Contents/MacOS/Traktor
Identifier:            com.native-instruments.Traktor
Version:               2.11.3 17 (2.11.3 17, Copyright © 2018 Native Instruments)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Traktor [14421]
User ID:               501

Date/Time:             2021-03-07 20:39:12.981 -0800
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        14039B6C-015A-F4D9-55CD-C0B1C2E64D97

Sleep/Wake UUID:       D76E1F2F-5A88-4CC1-88B8-6D0E769EF76C

Time Awake Since Boot: 17000 seconds
Time Since Wake:       480 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libQt5Qml.5.dylib             	0x000000010b601894 QQmlError::toString() const + 532
1   com.native-instruments.Traktor	0x000000010885d533 csi::qml::MappingLoader::load(QUrl, QQmlEngine*) + 739
2   com.native-instruments.Traktor	0x0000000107d5407d TProMappingLoader::load(char const*, QQmlEngine*) + 157
3   com.native-instruments.Traktor	0x0000000107f5dd59 DeviceIO::Devices::DeviceIOCSIBridge::initInternal(DeviceIOSystem*, bool, bool) + 105
4   com.native-instruments.Traktor	0x000000010807d46e DeviceIO::Devices::TraktorKontrol::D2::initInternal(DeviceIOSystem*, bool, bool) + 30
5   com.native-instruments.Traktor	0x0000000107f5a988 DeviceIOBase::init(DeviceIOSystem*, bool, bool) + 24
6   com.native-instruments.Traktor	0x0000000107eff498 DeviceIOManager::initDeviceIO(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool) + 408
7   com.native-instruments.Traktor	0x00000001082bdf2e PreferenceDialogPageDeviceIO::onControlEvent(unsigned int, unsigned int, NI::NGL::ControlEventData*) + 1294
8   com.native-instruments.Traktor	0x00000001084b4150 NI::NGL::Control::notifyListeners(unsigned int, NI::NGL::ControlEventData*, bool) + 256
9   com.native-instruments.Traktor	0x00000001084e0af7 NI::NGL::PopupMenu::selectEntry(NI::NGL::PopupMenu*, int, unsigned int, NI::UIA::EventData*) + 295
10  com.native-instruments.Traktor	0x00000001084e18ed NI::NGL::PopupMenu::onLButtonUp(NI::GP::Point, bool, bool, NI::UIA::EventData*) + 429
11  com.native-instruments.Traktor	0x00000001084df96c NI::NGL::PopupMenu::onEvent(unsigned int, NI::UIA::EventData*) + 460
12  com.native-instruments.Traktor	0x00000001084d0bd7 NI::NGL::Form::onMouseEvent(unsigned int, NI::UIA::MouseEventData*) + 87
13  com.native-instruments.Traktor	0x00000001084d0569 NI::NGL::Form::onEvent(unsigned int, NI::UIA::EventData*) + 57
14  com.native-instruments.Traktor	0x00000001084d5afd NI::NGL::FormManager::sendEvent(unsigned int, NI::UIA::EventData*) + 109
15  com.native-instruments.Traktor	0x00000001079b7e20 NI::NGL::Window<NI::UIA::PopupWindow>::onEvent(unsigned int, NI::UIA::EventData*) + 736
16  com.native-instruments.Traktor	0x0000000108263b52 TraktorModelessDialogBase::onEvent(unsigned int, NI::UIA::EventData*) + 210
17  com.native-instruments.Traktor	0x00000001082a5538 non-virtual thunk to PreferencesDialog::onEvent(unsigned int, NI::UIA::EventData*) + 152
18  com.native-instruments.Traktor	0x0000000108b61b1c NI::UIA::DETAIL::WindowImpl::sendEvent(unsigned int, NI::UIA::EventData*, bool) + 28
19  com.native-instruments.Traktor	0x0000000108b6f91a NI::UIA::COCOA::View::mouseUp(objc_object*, objc_selector*, NSEvent*) + 282
20  com.apple.AppKit              	0x000000010d50a713 -[NSWindow _handleMouseUpEvent:isDelayedEvent:] + 119
21  com.apple.AppKit              	0x000000010d50b3ad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
22  com.apple.AppKit              	0x000000010cf4a539 -[NSWindow sendEvent:] + 517
23  com.apple.AppKit              	0x000000010cecaa38 -[NSApplication sendEvent:] + 2540
24  com.native-instruments.Traktor	0x0000000108464072 -[NICocoaStandaloneApplication sendEvent:] + 98
25  com.apple.AppKit              	0x000000010cd31df2 -[NSApplication run] + 796
26  com.apple.Foundation          	0x000000010f78ee2e -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 1115
27  com.apple.Foundation          	0x000000010f78e955 -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 131
28  com.native-instruments.Traktor	0x00000001084642c8 main + 520
29  libdyld.dylib                 	0x0000000110f465ad start + 1

**Comment by ErikMinekus** [comment]
Thanks for the report, this has been fixed in commit 26a9f6b.
