### ISSUE TITLE
[Question] Is it possible to get he playlist?

### ISSUE THREAD

**Issue by lord-carlos** [ErikMinekus/traktor-api-client#10]
The D2 can show the playlist for track selection.

Would something similar be possible to implement?

Thank you for your time.

**Comment by ErikMinekus** [comment]
I think it is possible to send the list of tracks in the active playlist, but I don't see a use case for it.

**Comment by lord-carlos** [comment]
I'm just wondering of the possibility to create my own controller that has a display. Currently just an idea.
Thank you for your quick response.

**Comment by johndsexton** [comment]
I'd like to be able to send the currently selected browser tree item and currently selected playlist track data as json to a web browser. Then the  web browser can use tts js speech api to speak back the current browser selection. This would help anyone like me who can not see the text on controller displays.

**Comment by ihernanhergert** [comment]
Hi, i want to do a playlist of the browser of traktor in real time  to see in the oled screen of the arduino, i clone the repository but i can't achieve it, i will try again and if i do it i will response this thread, thx u guys
