### ISSUE TITLE
browser tree/list selected item

### ISSUE THREAD

**Issue by johndsexton** [ErikMinekus/traktor-api-client#12]
Is it possible to have the selected browser tree/list selected item sent via this client api?
I'm only looking for textual data, not graphical items.

**Comment by ErikMinekus** [comment]
Information about the browser list is not available from the CSI module where this API client currently resides. I would have to rewrite it and move it to the Screens folder, which would take time and make it harder to install and run next to any display mods. So unfortunately it's not something I'm interested in right now.
