### ISSUE TITLE
Made the mistake of upgrading to 3.5.1 Since then it does not work.

### ISSUE THREAD

**Issue by mhuca** [ErikMinekus/traktor-api-client#2]
I've been running on 3.3.x for some time and made the silly mistake of trying 3.5.1 since then I can get anything to work.

I can still receive traffic on my http server (Happens to be Node-red)

Is there anything that can be done to get it working again.

I've tried deleting the D2 folder and downloading a new copy.

my ApiClient.js has var API_BASE_URL = "http://10.0.x.x:1880" 

I've gone to Settings> Controller Manager and deleted and readded Traktor.Kontrol D2

Any help would be greatly appreciated.

**Comment by ErikMinekus** [comment]
Not sure, it still works for me with 3.5.1.

**Comment by mhuca** [comment]
Finally got it working again... had to reinstall everything... must have been a curruption somewhere...

FYI... Work well with Node-Red and OBS for showing the current track.
