### ISSUE TITLE
Can't manage to receive data

### ISSUE THREAD

**Issue by Lokixin** [ErikMinekus/traktor-api-client#3]
Hi, we're trying to use your library with Traktor Pro 3 in a Mac. We followed the instructions described in the Readme, but we do not receive any data. Do we need to run any script? We doubled checked that the traktor broadcasting is sending data to port 8080. Thanks!

**Comment by ErikMinekus** [comment]
Hi,

No, the instructions in the README are sufficient. I'm not sure what you mean by the Traktor broadcasting, it's not mentioned anywhere in the README that you need to configure broadcasting.

**Comment by djpeterlewis** [comment]
Hi Great idea you have here. I replaced the D2 folder then restarted and chose the D2 controller. Then I ran my webserver on port 4000/getsongs   which I setup to receive POST messages. I then checked it by going to my Browser and  typing in 
http://localhost:4000/getsongs
my server showed that I did get data by responding showing that was a GET 
getsongs
-1
http://localhost:4000/getsongs
(HttpInputOverHTTP) HttpInputOverHTTP@60410cd[c=0,q=0,[0]=null,s=STREAM]
GET
/getsongs
false

in the file .js I changed it to  var API_BASE_URL = "http://localhost:4000/getsongs"

then started Traktor loaded a long but received no info. I set the server up to receive ANYTHING.

Thank you again for this great idea . I look forward to hearing your comments

**Comment by djpeterlewis** [comment]
I managed to solve it , Thank you. I restricted the url and did not have /* on my server. Now it is receiving stuff. Thank you
/getsongs/updateDeck/A
false
getsongs
35
application/json;charset=UTF-8
http://localhost:4000/getsongs/updateDeck/D
(HttpInputOverHTTP) HttpInputOverHTTP@4ebff610[c=0,q=0,[0]=null,s=STREAM]
POST
/getsongs/updateDeck/D
false
getsongs
51
application/json;charset=UTF-8
http://localhost:4000/getsongs/updateDeck/A
(HttpInputOverHTTP) HttpInputOverHTTP@4ebff610[c=0,q=0,[0]=null,s=STREAM]
POST
/getsongs/updateDeck/A
false
getsongs
35
application/json;charset=UTF-8
http://localhost:4000/getsongs/updateDeck/D
(HttpInputOverHTTP) HttpInputOverHTTP@4ebff610[c=0,q=0,[0]=null,s=STREAM]
POST
/getsongs/updateDeck/D
false
getsongs
51
application/json;charset=UTF-8
http://localhost:4000/getsongs/updateDeck/A
(HttpInputOverHTTP) HttpInputOverHTTP@4ebff610[c=0,q=0,[0]=null,s=STREAM]
POST
/getsongs/updateDeck/A
false
getsongs
35
application/json;charset=UTF-8
http://localhost:4000/getsongs/updateDeck/D
(HttpInputOverHTTP) HttpInputOverHTTP@4ebff610[c=0,q=0,[0]=null,s=STREAM]
POST
/getsongs/updateDeck/D
false
getsongs
51
application/json;charset=UTF-8
