### ISSUE TITLE
What can of info is possible to send?

### ISSUE THREAD

**Issue by lautrip** [ErikMinekus/traktor-api-client#5]
Hi, I think this is brilliant.

I wanted to know what info is possible to send via this.

is it possible to pass real time track position?

I’m looking into having some kind of traktor video playback, maybe this is the key?

**Comment by ErikMinekus** [comment]
I've only been able to send messages via HTTP, which is not real time. I've also built in small delays in order to not spam the web server.

I'm already sending most of the information that's available, so just check the incoming messages.

**Comment by ChasonDeshotel** [comment]
First off, awesome job with this. I've been hacking away at this for quite a while now, got close, just hadn't had the time to dive deep

It's a shame you can't send UDP packets with XMLHttpRequest... I've run hundreds of LEDs with UDP over wireless with 1-2ms delay. All handled by an ESP8266... goes to show how much overhead is in the handshake

How many requests are we talking?

My use case is sending the current track tempo over MIDI to update the LCD on my turntables. This is a Reloop Serato-only function... I reverse engineered it and can update the tempo displays so the next step is get it out of Traktor (I created a [Python module](https://github.com/ChasonDeshotel/Reloop-RP-8000-MIDI/) cause Python had a great MIDI communication module) 

But I would prefer to send MIDI directly, or even write the tempo to a file and have a process that monitors and sends updates. How locked down is this codebase? Can we load modules? I tried to compile stuff with QT but I'm new with QT and if I managed to compile something I'm not even sure it could be used within Traktor

So, check it out, this is cute:
```
function saveFile(fileUrl, text) {
    var request = new XMLHttpRequest();
    request.open("PUT", fileUrl, false);
    request.send(text);
    return request.status;
}
```
Perfect for using that data locally.

I'll make a PR if I write anything useful that could be applied to what you've got here

Big up

**Comment by ChasonDeshotel** [comment]
@donmurdoc look at https://github.com/vladkorotnev/traktor-obs-relay

It uses this API to do some fancy things

>[](https://github.com/vladkorotnev/traktor-obs-relay#auto-vjhtml)auto-vj.html
>
>Plays video files stored by the same name as the played audio files automatically. Not guaranteed to be 100% in sync for obvious reasons. Supports webm and mp4 with opacity.

**Comment by lautrip** [comment]
> @donmurdoc look at https://github.com/vladkorotnev/traktor-obs-relay
> 
> It uses this API to do some fancy things
> 
> > auto-vj.html
> > Plays video files stored by the same name as the played audio files automatically. Not guaranteed to be 100% in sync for obvious reasons. Supports webm and mp4 with opacity.

Yes, after I posted this I discovered that project, its doope.
Thank you!.

**Comment by ChasonDeshotel** [comment]
Awesome! Glad it works well. I have it cloned but haven't had a chance to play with it yet.

Super appreciative for @ErikMinekus and @vladkorotnev's work. Been wanting this kind of functionality for years

Now if only NI would add sticker lock....

**Comment by alexweej** [comment]
Would you mind offering some advice on how to reverse engineer this? Ideally we can build a bit of an unofficial manual on the parameters. I am specifically interested in current loop position/length, and ensuring that the elapsed position is posted when paused and seeking around (via cue position).

Thanks

**Comment by knetur** [comment]
@ErikMinekus Excellent project, thank you!

If you don't mind, is it possible to get info from all decks simultaneous (playing or not)? Using external mixer (A&H Xone: 92) and audio interface with my D2s Traktor is unaware what deck is live. Would help me a bunch to know. If possible I'd jump into making a script myself.

Thanks again!

**Comment by ErikMinekus** [comment]
@knetur It already sends data for all decks simultaneously.

@alexweej You have to go to the qml folder mentioned in the readme and dig through the files, that's the way to learn what data is available.

**Comment by knetur** [comment]
@ErikMinekus Thanks for your response!
