### ISSUE TITLE
add "RELEASE DATE" Metadata

### ISSUE THREAD

**Issue by arnaudgst** [ErikMinekus/traktor-api-client#7]
Hello,

First many thanks for your amazing work :)

Is it possible to add "RELEASE DATE" Metadata ?

Regards,

Arnaud

**Comment by deg0nz** [comment]
I looked into this and it seems, that the release date is not available in track decks, so this feature will most likely not be available.

**Comment by ErikMinekus** [comment]
Indeed, release date is not exposed to QML unfortunately.
