### ISSUE TITLE
is thiss working? 

### ISSUE THREAD

**Issue by gkorthagen** [ErikMinekus/traktor-api-client#8]
I did the steps, but there is nothing listening on 8080:
netstat 
 TCP    0.0.0.0:135            SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:445            SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:2179           SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:5040           SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:5357           SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:7680           SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:49664          SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:49665          SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:49666          SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:49667          SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:49668          SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:49693          SurfaceLaptopGKO:0     LISTENING
  TCP    0.0.0.0:59407          SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:5146         SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:5556         SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:5563         SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:5939         SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:6463         SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:7865         SurfaceLaptopGKO:0     LISTENING
  TCP    127.0.0.1:49669        SurfaceLaptopGKO:49670  ESTABLISHED
  TCP    127.0.0.1:49670        SurfaceLaptopGKO:49669  ESTABLISHED
  TCP    127.0.0.1:49671        SurfaceLaptopGKO:49672  ESTABLISHED
  TCP    127.0.0.1:49672        SurfaceLaptopGKO:49671  ESTABLISHED
  TCP    127.0.0.1:49673        SurfaceLaptopGKO:49674  ESTABLISHED
  TCP    127.0.0.1:49674        SurfaceLaptopGKO:49673  ESTABLISHED
  TCP    127.0.0.1:49675        SurfaceLaptopGKO:49676  ESTABLISHED
  TCP    127.0.0.1:49676        SurfaceLaptopGKO:49675  ESTABLISHED
  TCP    127.0.0.1:49677        SurfaceLaptopGKO:49678  ESTABLISHED
  TCP    127.0.0.1:49678        SurfaceLaptopGKO:49677  ESTABLISHED
  TCP    127.0.0.1:49679        SurfaceLaptopGKO:49680  ESTABLISHED
  TCP    127.0.0.1:49680        SurfaceLaptopGKO:49679  ESTABLISHED
  TCP    127.0.0.1:49681        SurfaceLaptopGKO:49682  ESTABLISHED
  TCP    127.0.0.1:49682        SurfaceLaptopGKO:49681  ESTABLISHED
  TCP    127.0.0.1:49683        SurfaceLaptopGKO:49684  ESTABLISHED
  TCP    127.0.0.1:49684        SurfaceLaptopGKO:49683  ESTABLISHED
  TCP    127.0.0.1:49685        SurfaceLaptopGKO:49686  ESTABLISHED
  TCP    127.0.0.1:49686        SurfaceLaptopGKO:49685  ESTABLISHED
  TCP    127.0.0.1:49687        SurfaceLaptopGKO:49688  ESTABLISHED
  TCP    127.0.0.1:49688        SurfaceLaptopGKO:49687  ESTABLISHED
  TCP    127.0.0.1:49689        SurfaceLaptopGKO:49690  ESTABLISHED
  TCP    127.0.0.1:49690        SurfaceLaptopGKO:49689  ESTABLISHED
  TCP    127.0.0.1:49691        SurfaceLaptopGKO:49692  ESTABLISHED
  TCP    127.0.0.1:49692        SurfaceLaptopGKO:49691  ESTABLISHED
  TCP    172.28.0.1:139         SurfaceLaptopGKO:0     LISTENING
  TCP    172.28.0.1:5556        SurfaceLaptopGKO:0     LISTENING
  TCP    192.168.1.140:139      SurfaceLaptopGKO:0     LISTENING
  TCP    192.168.1.140:5556     SurfaceLaptopGKO:0     LISTENING
  TCP    192.168.1.140:49285    20.223.237.241:https   TIME_WAIT
  TCP    192.168.1.140:49288    52.178.17.3:https      TIME_WAIT
  TCP    192.168.1.140:49293    i-am3p-cor005:https    TIME_WAIT
  TCP    192.168.1.140:49294    20.60.88.36:https      TIME_WAIT
  TCP    192.168.1.140:49417    40.113.110.67:https    ESTABLISHED

**Comment by ErikMinekus** [comment]
This client sends data to localhost:8080, you need to create your own web server listening on port 8080.

**Comment by gkorthagen** [comment]
Ah ok. So its sends data to that port. So i must create a listener on that port. Didn't get that.

Thnx!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gkorthagen** [comment]
I setup a listener on port 8080.
I get the deck posting.  But not the other events...
